services:
  analytics:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=development
    environment:
      - DATABASE_PATH=/data/analytics.db
      - PORT=8080
      - ADDRESS=0.0.0.0
      - RATE_LIMIT_COUNT=15
      - CORS_ALLOWED_ORIGINS=*
      - TRUSTED_PROXIES=0.0.0.0
      - DASHBOARD_ENABLED=true
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
    restart: unless-stopped
