// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

type Instance struct {
	UUID     string `json:"uuid"`
	Version  string `json:"version"`
	LastSeen int64  `json:"last_seen"`
}
