// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
)

const createInstance = `-- name: CreateInstance :exec
INSERT INTO instances (
  uuid, version, last_seen
) VALUES (
  ?, ?, ?
)
`

type CreateInstanceParams struct {
	UUID     string
	Version  string
	LastSeen int64
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createInstance, arg.UUID, arg.Version, arg.LastSeen)
	return err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances
WHERE uuid = ?
`

func (q *Queries) DeleteInstance(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, uuid)
	return err
}

const deleteOldInstances = `-- name: DeleteOldInstances :many
DELETE FROM instances
WHERE last_seen < ?
RETURNING uuid, version, last_seen
`

func (q *Queries) DeleteOldInstances(ctx context.Context, lastSeen int64) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, deleteOldInstances, lastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(&i.UUID, &i.Version, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInstances = `-- name: GetAllInstances :many
SELECT uuid, version, last_seen FROM instances
`

func (q *Queries) GetAllInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, getAllInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(&i.UUID, &i.Version, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstance = `-- name: GetInstance :one
SELECT uuid, version, last_seen FROM instances
WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetInstance(ctx context.Context, uuid string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, uuid)
	var i Instance
	err := row.Scan(&i.UUID, &i.Version, &i.LastSeen)
	return i, err
}

const updateInstance = `-- name: UpdateInstance :exec
UPDATE instances
set last_seen = ?
WHERE uuid = ?
`

type UpdateInstanceParams struct {
	LastSeen int64
	UUID     string
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, updateInstance, arg.LastSeen, arg.UUID)
	return err
}
